import express from 'express';
import { authenticationToken } from '../../middleware/auth/authenticationMiddleware';
import { addMedicalRecord } from '../../service/impl/medicalRecord/addMedicalRecord/addMedicalRecord.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateMedicalRecord } from '../../validator/validator';
import { showMedicalRecords } from '../../service/impl/medicalRecord/showMedicalRecords/showMedicalRecords.impl';
import { showMedicalRecord } from '../../service/impl/medicalRecord/showMedicalRecord/showMedicalRecord.impl';
const router = express.Router();
router.post('/add-medical-record', authenticationToken, globalValidator(validateMedicalRecord), addMedicalRecord);
router.get('/show-medical-records', authenticationToken, showMedicalRecords);
router.get('/show-medical-record/:id', authenticationToken, showMedicalRecord);
export default router;