import express from 'express';
import { register } from '../../service/impl/auth/register/register.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateUserLogin, validateUserRegisteration } from '../../validator/validator';
import { login } from '../../service/impl/auth/login/login.impl';
import { authenticationToken } from '../../middleware/auth/authenticationMiddleware';
import { logout } from '../../service/impl/auth/logout/logout.impl';
import { fetchUsers } from '../../service/impl/auth/retrieveUsers/fetchUsers.impl';
import { fetchUser } from '../../service/impl/auth/fetchUser/fetchUser.impl';
const router = express.Router();
router.post('/create-account', globalValidator(validateUserRegisteration), register);
router.post('/login', authenticationToken, globalValidator(validateUserLogin), login);
router.post('/logout', authenticationToken, logout);
router.get('/fetch-users', authenticationToken, fetchUsers);
router.get('/fetch-user/:id', authenticationToken, fetchUser);
export default router;