import express from 'express';
import { authenticationToken } from '../../middleware/auth/authenticationMiddleware';
import { addADoctor } from '../../service/impl/doctor/addDoctor/addDoctor.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { validateAddADoctorRequest, validateUpdatedDoctorRequest } from '../../validator/validator';
import { showDoctors } from '../../service/impl/doctor/showDoctors/showDoctors.impl';
import { showDoctor } from '../../service/impl/doctor/showDoctor/showDoctor.impl';
import { updateDoctor } from '../../service/impl/doctor/updateDoctor/updateDoctor.impl';
import { deleteDoctor } from '../../service/impl/doctor/deleteDoctor/deleteDoctor.impl';
const router = express.Router();
router.post('/add-doctor', authenticationToken, globalValidator(validateAddADoctorRequest), addADoctor);
router.get('/show-doctors', authenticationToken, showDoctors);
router.get('/show-doctor/:id', authenticationToken, showDoctor);
router.put('/update-doctor/:id', authenticationToken, globalValidator(validateUpdatedDoctorRequest), updateDoctor);
router.delete('/delete-doctor/:id', authenticationToken, deleteDoctor);
export default router;